# Generated by Django 4.1 on 2023-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_face_encoding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="latecomer",
            name="employee",
        ),
        migrations.AddField(
            model_name="latecomer",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="User Fires Name"
            ),
        ),
        migrations.AddField(
            model_name="latecomer",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="User Last Name"
            ),
        ),
    ]
